# -*- coding: utf-8 -*-
"""Eskom_SA_Loadshedding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBY-DcacJYa31JTwDG4gDwtQwD_c8qJe

# The Natural Language Understanding (NLU) task of unstructured data (Tweets) collected from Eskom_SA Twitter account. The goal is to gain an insight into the data by performing Lexical, Syntactic and Semantic analysis of the dataset.

# Data Loading
"""

# Import libraries
import pandas as pd                       # library for data analysis and data manipulation
import numpy as np                        # library used for working with arrays 
import spacy                              # library used for information extraction 
import os                                 # library for interacting with the operating system
import stanza                             # library for analysis of human languages
stanza.download('en')
from spacy import displacy

from collections import Counter

# Text preprocesing library
import re                                   # library for regular expression operations
import string                               # library for string operations

import nltk                                 # collection of libraries for natural language processing
from nltk.corpus import stopwords           # module for stop words that comes from NLTK
from nltk.stem import PorterStemmer         # module for stemming
from nltk.tokenize import TweetTokenizer    # module for tokenizing strings
from nltk.tree import Tree
from nltk.corpus import wordnet             # module for a lexical database of English
from nltk.stem import WordNetLemmatizer     # module for lemmatization

nltk.download('stopwords')                  # download a stop word
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk import pos_tag, word_tokenize

import matplotlib.pyplot as plt            # library used for data visualization
import seaborn as sns                      # library based on matplotlib, provides a high-level interface for data visualization
from wordcloud import WordCloud            # library to visualize text data


from IPython.display import display

nlp = spacy.load('en_core_web_sm')

os.environ['PATH'] = os.environ['PATH']+";C:\\Program Files\\gs\\gs9.55.0\\bin\\"

data = pd.read_excel('Eskom_SA_Loadshedding.xlsx')    # read the excel data of the already downloaded tweets
  
header = data.iloc[0]        # make the 2nd row the header
data.columns = header.values
data = data[1:]      # remove the second row from data

data.head() # preview the data

"""# Data Preprocessing

The preprocessing at this stage will leverage NLTK tool which will involves the following cleaning process: 

1. Eliminate twitter handle and url
2. Tokenizing the string into list of word
3. Lowercasing
4. Stop word and Punctuation removal
5. Stemming e.g buying, buys becomes buy
6. Lemmatization - converting a word to its base form

# Lexical Analysis
"""

def remove_handle_url_hash_sign(tweet):
    """remove twitter handle and and url from the tweet

    Args:
        tweet (str): raw tweet from the coallated tweets
    Return: 
    
    """
    
    tweet = re.sub(r'https?://[^\s\n\r]+', '', tweet) # remove hyperlink
    tweet = re.sub(r'@[^\s\n\r]+', '', tweet) # remove @ sign of twitter handle tag  
    tweet = re.sub(r'#', '', tweet) # remove hashtag 
    tweet = re.sub(r'[^\w\s]','', tweet) #remove punctuations
    
    return tweet
    
def tokenize_and_stem(tweet):
    """
    Tokenize - meaning convert the sntence into list of word, after which all data will be lowercased, stopword removed 
    and punctuation also removed. For the TOkenization will utiliize Twitter tokenization from NLTK library

    Args:
        tweet (string): returns 
    
    Return 
        (list): A list of cleaned tweet tokeized without stop word and punctuation
    
    """
    
    # Tokenize sentence using the Twitter tokenizer
    tweet_tokenizer = TweetTokenizer(strip_handles=True, preserve_case=False, reduce_len=True)
    tokenized_tweet = tweet_tokenizer.tokenize(tweet)
    
    
    stemmer = PorterStemmer()          # define stemmer type
    wordnet_lemmatizer = WordNetLemmatizer()
    stopwords_english = stopwords.words('english')   # Get list of available stopword  
    
    
    tweets_clean = []

    for word in tokenized_tweet: # Go through every word in your tokens list
        if (word not in stopwords_english and  # remove stopwords
                 word not in string.punctuation):  # remove punctuation
            # stem_word = stemmer.stem(word)        # stem the word; try also lemming of the data.
            lemmatizer_word = wordnet_lemmatizer.lemmatize(word, pos='v')    # lemmatize for verb
            lemmatizer_word = wordnet_lemmatizer.lemmatize(lemmatizer_word, pos='n') # lemmatize for noun
            
            tweets_clean.append(lemmatizer_word)
            
    return tweets_clean

def test_preprocessing(tweed_id, data, col):
    """tests case for checking if the data was printed correctly the tweet data

    Args:
        tweed_id (int): index of the tweet in the data
        data (DataFrame): full dataframe where the tweet contains
        col (string): column where the tweet data is located in sample case it will be 'Tweet Text'
    Returns:
        prints out tweet before processing and after processing.
    """
    test_tweet = data.iloc[tweed_id][col]
    print('\033[90m', 'Raw_data, Before handle, url and hash sign removal')
    print('\033[91m', test_tweet)
                
    print()
    print('\033[90m', 'After using Handle, url and hash sign removal')
    processed_tweet_1 = remove_handle_url_hash_sign(test_tweet)
    print('\033[92m', processed_tweet_1)
    
    print()
    print('\033[90m', 'After tokenizing and steming')
    processed_tweet_2 = tokenize_and_stem(processed_tweet_1)
    print('\033[94m', processed_tweet_2)

data['Tweet Text'].iloc[95]

# test the handling methodology
test_preprocessing(211, data, 'Tweet Text')

"""# Text Analysis and Visualization

This is aimed at gaining a wide range of understanding of the text involved in the data or the tweets. It's a very simple methodology in having a high-level view on what is going on with the data provided and available.

1. Get the Number of words in Tweet
2. Number of characters
3. Show the most frequent word
4. Do a word cloud of the available words

"""

# Clean and preprocess cleaned data
data['Tweet_No_url_cleaned'] = data['Tweet Text'].apply(remove_handle_url_hash_sign)
data['Tokenized_tweet'] = data['Tweet_No_url_cleaned'].apply(tokenize_and_stem)

# Get statistics of tweet
data['Number of Tweet Word'] = data['Tokenized_tweet'].apply(len)
data['Number of Tweet Character'] = data['Tweet_No_url_cleaned'].apply(len)

data[['Tweet Text', 'Tweet_No_url_cleaned', 'Tokenized_tweet']].head() # preview of the cleaned tweet

"""# Text Visualization"""

# plt.figure(figsize=(8, 4))
fig, axs = plt.subplots(nrows=1, ncols=1, figsize=(8, 4))

data['Number of Tweet Word'].plot(kind='hist', color='blue', 
                                       label='Number of Words in a Tweet', alpha=0.6)
plt.legend()
plt.xlabel("Number of Word in a Tweet")
plt.title('Distribution of the Number of Word in a Tweet')

"""It is interesting to note that there is a high frequency of number of tweet words in the range 10 - 15."""

# plt.figure(figsize=(8, 4))
fig, axs = plt.subplots(nrows=1, ncols=1, figsize=(8, 4))

data['Number of Tweet Character'].plot(kind='hist', color='orange', 
                                       label='Number of Characters in a Tweet', alpha=0.6)
plt.legend()
plt.xlabel("Number of Word in a Characters")
plt.title('Distribution of the Number of Characters in a Tweet')

# Visualise most common tweet in the data
all_tweet_word = Counter([word for row in data['Tokenized_tweet'] for word in row ])
top_20_common_word = all_tweet_word.most_common(20)

df_top_20_common_word = pd.DataFrame(top_20_common_word)
df_top_20_common_word.columns = ['Words', 'Number']

df_top_20_common_word.style.background_gradient(cmap='Oranges')

# Word Count of the tweet
all_text = ''

for row in data['Tokenized_tweet']:
    for word in row:
        all_text = all_text+(word + ' ')

wc = WordCloud(background_color="white", repeat=True)
wc.generate(all_text)

plt.axis("off")
plt.imshow(wc, interpolation="bilinear")

"""# Syntactic Analysis

   The structure of the tweet as depicted in the data. An indepth analaysis of the syntax involved in this tweet data using 
   the  following attributes:
 
  - Date: The day the tweet was initiated.
  - Screen Name: A twitter handle or a username that is set up when a user first creates a Twitter account.
  - Fullname: Name of the tweet originator.
  - Tweet Text: The information or text containing the tweet. This is about the product or the consumer of interest.
  - Tweet ID: The unique id attributed to the tweet on Twitter database.
  - Location: The location of the Twitter user.
  - Retweets: The number of retweets attributed and done on the tweet
  - Type of App: The device used by the user in tweeting.
  
"""

# Specify the appropriate data column for the structure
structure_col = ['Screen Name','Full Name', 'Tweet Text', 'Tweet ID', 
 'Location_text', 'Retweets', 'App','Date']

# Renaming the column name to deal with issue of duplicated column name 'location'
data.columns = ['Date', 'Screen Name', 'Full Name', 'Tweet Text', 'Tweet ID', 'Link(s)',
       'Media', 'Location', 'Retweets', 'Favorites', 'App', 'Followers',
       'Follows', 'Listed', 'Verfied', 'User Since', 'Location_text', 'Bio',
       'Website', 'Timezone', 'Profile Image', 'Tweet_No_url_cleaned',
       'Tokenized_tweet', 'Number of Tweet Word', 'Number of Tweet Character']

# Draw tree parse of the tweet data structure
message_text_tree = Tree('message_text',['hash_tag', 'at_user', 'other_text_sequence', 'url'])
message_data_tree = Tree('message_data',[message_text_tree,'tweet_id','time','location', 'type_of_App'] )
statistic_info_tree = Tree('statistic_info', ['followers', 'retweets'])
user_data_tree = Tree('user_data', ['full_name', 'user_name'])
tree_P1 = Tree('TD (Tweet Data)', [user_data_tree, statistic_info_tree,message_data_tree])
print('<============================================Parse tree of the tweet data================================================>')
display(tree_P1)
tree_P1.pretty_print(unicodelines=True,ansi =True, nodecolor='blue',nodedist=1)  # Draw parse tree without white background

# Print a sample struture of the text data
sample_tweet = data[structure_col].T[[501]]
sample_tweet.columns = [ 'Values']

headers = {
    'selector': 'th:not(.index_name)',
    'props': 'background-color: green; color: white;'
}

sample_tweet.style.set_table_styles([headers])

# sample_tweet data struture of the text

def Part_of_Speech_Parse(data, row_index, tweet_column):
    sentence = str(data.iloc[row_index][tweet_column])
    sentence_nlp = nlp(sentence)

    # POS tagging with Spacy 
    spacy_pos_tagged = [(word, word.tag_, word.pos_) for word in sentence_nlp]
    df_spacy_tag = pd.DataFrame(spacy_pos_tagged, columns=['Word', 'POS tag', 'Tag type'])

    # POS tagging with nltk
    nltk_pos_tagged = nltk.pos_tag(sentence.split())
    df_nltk_tag = pd.DataFrame(nltk_pos_tagged, columns=['Word', 'POS tag'])

    return df_spacy_tag, df_nltk_tag
Part_of_Speech_Parse(data, row_index=3, tweet_column='Tweet Text')

"""# Sentiment Analysis"""

from textblob import TextBlob

from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download("vader_lexicon")

data[['Tweet Text']].head(5)

data.shape # Finding the shape of dataset

data.isna().sum() # Return the number of missing values

# Add labels to the dataset and calculate the sentiment scores
sentiments = SentimentIntensityAnalyzer()
data["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in data["Tweet Text"]]
data["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in data["Tweet Text"]]
data["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in data["Tweet Text"]]
data['Compound'] = [sentiments.polarity_scores(i)["compound"] for i in data["Tweet Text"]]
data[['Tweet Text', 'Positive', 'Negative', 'Neutral', 'Compound']].head(5)

# Add labels by categorizing the sentiment scores
score = data["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
data["Sentiment"] = sentiment
data[['Tweet Text', 'Positive', 'Negative', 'Neutral', 'Compound', 'Sentiment']].head()

print(data["Sentiment"].value_counts())

# Pie chart, where the slices will be ordered and plotted counter-clockwise:
labels = data["Sentiment"].value_counts().index.to_list()
sizes = data["Sentiment"].value_counts(normalize=True).to_list()
explode = (0, 0.05, 0)  # only "explode" the 2nd slice (i.e. 'Hogs')

fig1, ax1 = plt.subplots()
ax1.pie(sizes, explode=explode, labels=labels, autopct='%1.1f%%',
        shadow=True, startangle=90)
ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.title('Ratio of Sentiment in the Tweet')
plt.show()

"""# Visualise the wordcloud of the dataset"""

# Visualize the frequent words
import matplotlib.pyplot as plt

all_words = " ".join([sentence for sentence in data['Tweet Text']])

from wordcloud import WordCloud
wordcloud = WordCloud(width=800, height=500, random_state=42, max_font_size=100).generate(all_words)

# Plot the graph
plt.figure(figsize=(15,8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

"""# Natural Language Generation Task - Generating synthesized comments for the dataset"""

from nltk.corpus import wordnet as wn

import re

# Wordnet
# Get the list of possible keyword from user based on the different pattern in the tweet

list_words=['happy', 'sad','risk', 'warnings', 'timings','question','damage','increase', 'vandalism']


list_syn={}

for word in list_words:
    synonyms=[]
    for syn in wordnet.synsets(word):     # Find the synonmy of the desired word in wordnet library
        for lem in syn.lemmas():
            # Remove any special characters from synonym strings
            lem_name = re.sub('[^a-zA-Z0-9 \n\.]', ' ', lem.name())
            synonyms.append(lem_name)

    list_syn[word]=set(synonyms)

print (list_syn)

# Generate possible text from this keyword
# Building dictionary of intents & keywords
keywords={}
keywords_dict={}

for key_word in list_words:
  keywords[key_word]=[]
  
  for synonym in list(list_syn[key_word]):
    keywords[key_word].append('.*\\b'+synonym+'\\b.*')

for intent, keys in keywords.items():

    # Joining the values in the keywords dictionary with the OR (|) operator updating them in keywords_dict dictionary

    keywords_dict[intent]=re.compile('|'.join(keys))

print (keywords_dict)

# Defining possible responses from the user intent based on 5 key categories:

# 1. Positive sentiment
# 2. Negative sentiment
# 3. Inquiry about the timing of loadshedding
# 4. Comments on vandalism/damage/
# 5. Comments on price hike in power supply

# Building a dictionary of responses

responses={
    'happy':['Thank you for reiterating our commitment to always providing excellent service'],
    'sad': ['Eskom is implementing efforts to achieve operational stability and to restore the security of energy supply for the country. We apologize for any inconvenience caused.', 
            'To check what the position is of load shedding at any time, please go to loadshedding.eskom.co.za. Thank you!'],
    'question':['To check what the position is of load shedding at any time, please go to loadshedding.eskom.co.za. Thank you!'],
    'risk':['Eskom is implementing efforts to achieve operational stability and to restore the security of energy supply for the country.'],
    'timings':['To check what the position is of load shedding at any time, please go to loadshedding.eskom.co.za. Thank you'],
    'damage':['Eskom losing millions of rands to vandalism & infrastructure theft, communities are inconvenienced when their electricity supply is interrupted. It is a criminal offence to damage Eskom property. Report offenders to the local @SAPoliceService or Eskom on 0800 11 27 22.'],
    'increase': ["The price hike is partly being driven by purchases from independent power producers (IPPs) and carbon taxes – two costs that are outside of Eskom's direct control."],
    'vandalism':['Eskom losing millions of rands to vandalism & infrastructure theft, communities are inconvenienced when their electricity supply is interrupted. It is a criminal offence to damage Eskom property. Report offenders to the local @SAPoliceService or Eskom on 0800 11 27 22.'],
    'warnings':['Eskom is implementing efforts to achieve operational stability and to restore the security of energy supply for the country.']
}

